### ISSUE TITLE
Feature request: `Mock.calledWith`

### ISSUE THREAD

**Issue by maikthomas** [atabel/server-mocker#4]
Although you can currently ensure the api calls are correct by making the api call mock fields specific, sometimes data like a JSON.stringify'd array may have a different order while still being correct. 
In this scenario, it would be useful to have a calledWith method for the server mock where you could unpack and inspect data.

**Comment by atabel** [comment]
I've just published 1.4.0 with a new method `mockImplementation` that can be used for this purpose.
There is a [test case](https://github.com/atabel/server-mocker/blob/master/src/__tests__/integration-test.js#L49) with an example
